### ISSUE TITLE
Fiat-Währungen rausnehmen// Satzbau

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#10]
![issue5 png](https://user-images.githubusercontent.com/31703661/36563407-4a9baf1c-181a-11e8-9341-4021c3a66e7f.PNG)

Text bitte tauschen zu:

Tauschkrypto.de ist der allererste deutsche Kryptobroker, welcher den Austausch von Altcoins und Bitcoins gegen verschiedenste Kryptowährungen ermöglicht.
Höchste Qualität, akkurate Datenübermittlungsprozesse welche den höchsten Sicherheitsstandards entsprechen und vollste Anonymität zeichnen unseren Service aus.

**Comment by Aracher17** [comment]
fixed
