### ISSUE TITLE
Tauschen zu "Fehlt Ihre Lieblingswährung bzw. Coin?"

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#11]
![issue6](https://user-images.githubusercontent.com/31703661/36563557-c62ea31e-181a-11e8-9d31-b422ce3528c0.PNG)

**Comment by Aracher17** [comment]
Geht's hierbei um die Überschrift oder dem Text vor der der Mail adresse @mchlcrnsch ?
