### ISSUE TITLE
Zu viele Kommata mayne

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#12]
![issue7](https://user-images.githubusercontent.com/31703661/36563647-1fc737e2-181b-11e8-84b3-0b555ce07aa8.PNG)

Tauschen zu:

Der Betrag der dir angezeigt wird, ist der exakte Betrag, den du erhältst.

**Comment by Aracher17** [comment]
hab Du dann auch nochmal gegen Sie getauscht

**Comment by Aracher17** [comment]
Der Betrag der Ihnen angezeigt wird, ist der exakte Betrag, den Sie erhalten werden.
