### ISSUE TITLE
Komma

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#14]
![issue9](https://user-images.githubusercontent.com/31703661/36564030-369959cc-181c-11e8-834d-47a2f8ed3dc3.PNG)

Tauschen zu:
Geben Sie Ihren gewünschten Betrag, die Währung die Sie austauschen- und die Währung die Sie erhalten möchten, an. Möchten sie e. g. 1,3 BTC ausgeben um LTC zum angezeigten Kurs zu kaufen, geben sie „1.3“ ein und klicken auf „LOS GEHT'S“.

**Comment by Aracher17** [comment]
fixed
