### ISSUE TITLE
Logo in Schwarz/Weiß einfügen

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#21]
![issue16](https://user-images.githubusercontent.com/31703661/36564795-cf6043e4-181e-11e8-8c53-cd2ac7dd2003.PNG)

Unser Logo einfügen, statt des Astronauten ?

**Comment by Aracher17** [comment]
Würde - denke ich - nicht gut aussehen 
Hier wären zwei logo's die in SW wären
![example1](https://user-images.githubusercontent.com/16821682/36567821-089620da-1828-11e8-8417-2ba400b84429.PNG)
![example2](https://user-images.githubusercontent.com/16821682/36567822-08b5505e-1828-11e8-963c-ecc25304f721.PNG)

Was du bedenken musst, ist das wir pech schwarze icons dort haben, die alle sehr dünn gezeichnet sind. Unser logo würde die ganze Ruhe da einmal völlig zerstören. ich denke da müssen wir uns was besseres ausdenken! @mchlcrnsch
