### ISSUE TITLE
KW-Set berücksichtigen

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#22]
[Kopie von Tauschkrypto-KW(2288).xlsx](https://github.com/Aracher17/tauschkrypto-frontend/files/1749606/Kopie.von.Tauschkrypto-KW.2288.xlsx)

![issuex](https://user-images.githubusercontent.com/31703661/36565354-7d3359e2-1820-11e8-996d-43670310008a.PNG)

"Kryptobörse Made In Germany" ??

**Comment by Aracher17** [comment]
SEO ja, design irgendwie nein 
Das wird denn sehr lang und sieht kaum noch sexy herunter gebrochen aus.

meinung? @mchlcrnsch :
![showing](https://user-images.githubusercontent.com/16821682/36567991-bc7ee4ce-1828-11e8-9546-69328ca8f9b8.PNG)

**Comment by Aracher17** [comment]
![goampuja](https://user-images.githubusercontent.com/16821682/36568469-676c0c26-182a-11e8-9784-64aa0efd1c45.PNG)
