### ISSUE TITLE
Das kleine Logo und die Kurzbeschreibung

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#23]
![issuey](https://user-images.githubusercontent.com/31703661/36565724-a41890ee-1821-11e8-9436-c315f722bc83.PNG)

Link zu : Tauschkrypto.de - der erste anonyme Kryptoexchange Deutschlands.
Kurzbeschreibung zu:
Wir sind die erste anonyme Kryptobörse Deutschlands. Wir unterstützen eine Vielzahl von Kryptowährungen und werden in Zukunft noch viele weitere Altcoins listen. Als deutscher Finanzdienstleister im Bereich Kryptowährungen, bieten wir Ihnen eine dezentrale Lösung zu den zentral gespeicherten Exchangewallets.

---> daran denken dass das kleine Logo im TAB unseres ist.

**Comment by Aracher17** [comment]
der bug besteht nur, da die aktuellste version nicht auf dem server ist!
