### ISSUE TITLE
Bild unpassend

### ISSUE THREAD

**Issue by mchlcrnsch** [Aracher17/tauschkrypto-frontend#24]
![issuez](https://user-images.githubusercontent.com/31703661/36566567-2ac2e926-1824-11e8-8c1a-9ae48b7c1748.PNG)

Mögliche Fotos:

https://unsplash.com/photos/Khqmo4T-rs0

Ich finde dies hier ganz gut. Muss evtl. noch ein wenig aufgehellt werden, damit es einladender wirkt.
---->         https://unsplash.com/photos/oThnHPkb3p8

**Comment by Aracher17** [comment]
![unstimmigkeit](https://user-images.githubusercontent.com/16821682/36568202-61c62370-1829-11e8-94e8-a348e342de81.PNG)

weiss ich jetzt nicht.... das erste geht nicht weil das hochkant ist
